# -*- coding: utf-8 -*-
"""Approved Video 7 H.I.T. script, extracted verbatim from the canonical file.

Source: Video_7_Code_Prompt_HIT_Final.txt, between the BEGIN/END fences.
Extracted programmatically; no wording is retyped.
"""

LINES = [
    'Some of the hardest work to prove is the work that made everything else possible.',
    'In one senior people role, I joined a global remote-first company where parts of the change, onboarding, governance and organizational-effectiveness infrastructure were still incomplete.',
    'I wasn’t building everything from zero. I was building while operating — solving immediate needs while helping create the mechanisms future work could rely on.',
    'I’ll show you how to reconstruct the before, make your judgment visible and keep proof of work that can otherwise disappear once the system starts functioning.',
    '[SLIDE: Core Distinction]',
    'I’m Temidayo Afonja. I help experienced professionals understand what their work has built in them, what can travel and how to make that value easier to see when the context changes.',
    'There is a particular evidence problem when you are early in a function, first in a role, or responsible for building infrastructure that is not yet mature.',
    'Once the work starts functioning, the organization sees the process.',
    'The meeting.',
    'The rhythm.',
    'The dashboard.',
    'The onboarding experience.',
    'The governance mechanism.',
    'The program that now operates across regions.',
    'What becomes harder to see is everything that had to happen before those things could work reliably.',
    'And that is why foundational work can become invisible surprisingly quickly.',
    '[SLIDE: The Invisible-Work Problem]',
    'Think about what happens after you build something useful.',
    'A process that once needed constant explanation becomes normal.',
    'A decision that once required five conversations becomes part of a regular operating rhythm.',
    'People begin using language that previously did not exist.',
    'Ownership becomes clearer.',
    'A program that once had to be built and launched becomes part of how the organization operates across regions.',
    'The organization starts treating the mechanism as though it was always there.',
    'That is success.',
    'But it creates an evidence problem.',
    'Because later, when someone asks:',
    '“What exactly did you do?”',
    'you may describe the thing that exists now instead of the conditions you had to create before it could exist.',
    'So the first step is to reconstruct the before.',
    '[SLIDE: Reconstruct the Before]',
    'Do not start with:',
    '“I built a program.”',
    'Start with:',
    'What was incomplete, inconsistent or difficult before the work?',
    'And be precise.',
    'In my case, I would not say:',
    '“Nothing existed.”',
    'That would not be true.',
    'The better description is that parts of the surrounding people-capability and organizational-effectiveness infrastructure were not yet operating at the level the organization needed.',
    'That included areas such as change-management infrastructure, operating-model governance, leadership enablement, onboarding and the mechanisms that helped work move across functions.',
    'That is a very different claim from:',
    '“I created everything.”',
    'Accuracy makes the story stronger.',
    '[SLIDE: Before Questions]',
    'To reconstruct the before, ask four questions.',
    'What could people not do reliably yet?',
    'Where was ownership unclear?',
    'What depended too heavily on individual effort or informal relationships?',
    'And what happened every time the same problem returned?',
    'That is your baseline.',
    'It may not be a clean number.',
    'Foundational work often begins before the organization has good measurement.',
    'But there was still a starting condition.',
    'Maybe decisions took too long.',
    'Maybe teams solved the same problem repeatedly.',
    'Maybe the work could not scale.',
    'Maybe leaders were operating without a shared mechanism.',
    'The goal is not to make the “before” sound worse than it was.',
    'The goal is to make the starting condition visible enough that someone can understand why building the infrastructure mattered.',
    '[SLIDE: Show the Judgment]',
    'The second step is to show the judgment inside the building work.',
    'This matters because “I built a process” can make complex work sound administrative.',
    'But the process itself may not have been the hard part.',
    'The hard part may have been deciding:',
    'What should be standardized?',
    'What still needed flexibility?',
    'Who had to own which decision?',
    'Where should information move?',
    'What needed to become repeatable?',
    'What could not be solved inside one function?',
    'And what had to be true before people would actually use the mechanism you were building?',
    'That is where the capability sits.',
    '[SLIDE: Built From Scratch Does Not Mean Built Alone]',
    'And there is an important boundary here.',
    'Building something from scratch does not mean doing everything yourself.',
    'In that chapter of my career, I led work and built with my team and in partnership with leaders.',
    'That distinction matters.',
    'Foundational leadership often means creating enough clarity, governance and shared ownership for other people to do their work better.',
    'The contribution may be:',
    'the operating model;',
    'the decision rhythm;',
    'the integration mechanism;',
    'the shared language;',
    'the leadership capability;',
    'the program that can scale across regions;',
    'or the relationships that allowed several functions to move together.',
    'So do not inflate your story into:',
    '“I built all of this.”',
    'Ask instead:',
    'What part of the infrastructure was I responsible for making possible?',
    'That is a much more defensible explanation.',
    '[SLIDE: Building While Operating]',
    'One of the things that chapter taught me was how to build while operating.',
    'The business did not stop while the infrastructure was being built.',
    'Immediate workforce needs still had to be handled.',
    'Leaders still needed support.',
    'Change was still happening.',
    'Integration work still had deadlines.',
    'A global CSR program still had to move from idea to launch and then scale across regions.',
    'So part of the job was solving today’s problem while creating mechanisms that would make the next version of the problem easier to handle.',
    'And over time, there were visible signs that the operating environment had changed.',
    'Within about twelve months, People had become a more regular input into executive planning.',
    'In the onboarding redesign I led with my team, one measure of how well new hires felt integrated moved from 47 to 75.',
    'During a post-acquisition integration chapter, the integration work was completed within 90 days with no critical talent loss.',
    'And the global CSR program launched and scaled across all regions.',
    'Those are different pieces of evidence.',
    'I would not combine them into one dramatic claim.',
    'They show different things.',
    'One speaks to operating influence.',
    'One speaks to onboarding.',
    'One speaks to integration execution.',
    'One speaks to building a program that could operate across regions.',
    'The point is not that one mechanism caused all four.',
    'The point is that the work left evidence behind.',
    '[SLIDE: Keep the Proof]',
    'The third step is to preserve that evidence before the infrastructure becomes normal.',
    'Because once something works, memory simplifies it.',
    'People remember:',
    '“We have onboarding.”',
    '“We have a governance process.”',
    '“We have a leadership rhythm.”',
    '“We have a global program.”',
    'They may not remember why it was needed, what you had to decide or what changed while it was being built.',
    'So for foundational work, capture four things.',
    'The starting condition.',
    'What was incomplete, unclear or difficult?',
    'Your judgment.',
    'What did you have to decide, interpret or design?',
    'What you built with others.',
    'What mechanism, process, rhythm, program or infrastructure became possible?',
    'The evidence.',
    'What changed that you can truthfully and safely point to?',
    '[SLIDE: Proof Without Overclaiming]',
    'And the wording matters.',
    'Instead of:',
    '“I transformed onboarding.”',
    'I can say:',
    '“I led an onboarding redesign with my team, and one measure of how well new hires felt integrated moved from 47 to 75.”',
    'Instead of:',
    '“I transformed executive decision-making.”',
    'The defensible version is:',
    '“Within about twelve months, People had become a more regular input into executive planning.”',
    'Instead of:',
    '“I single-handedly built a global CSR function.”',
    'The defensible version is:',
    '“I launched a global CSR program that scaled across all regions.”',
    'And instead of:',
    '“I saved millions through retention.”',
    'I am not using that claim here.',
    'There were broader retention and turnover-cost outcomes during this chapter, but without the underlying calculation and attribution in front of me, they do not belong in this story.',
    'That is an important evidence discipline.',
    'A smaller claim you can defend is more useful than a larger claim you cannot.',
    '[SLIDE: What Did the Building Form?]',
    'Now ask the Capability Formation question.',
    'What did building this make you able to do?',
    'Maybe you learned to enter ambiguity without waiting for perfect instructions.',
    'Maybe you learned to create operating mechanisms while the work was still moving.',
    'Maybe you learned to work across functions where ownership was distributed.',
    'Maybe you learned to turn informal knowledge into something repeatable.',
    'Maybe you learned how to build a program that could scale across regions.',
    'Maybe you learned what had to exist before a function could perform reliably.',
    'That is where the portability starts to appear.',
    'Because the infrastructure itself may belong to one employer.',
    'The exact program may not travel.',
    'The company language may not travel.',
    'But some of the judgment can.',
    'And this is the line I want you to remember:',
    'Sometimes the most transferable part of being first is what you had to learn before the role could work at all.',
    'That is often the part that disappears from the résumé first.',
    '[SLIDE: Make Invisible Work Visible]',
    'If you have built something that is now taken for granted, write down:',
    'What was incomplete before?',
    'What judgment did the work require from me?',
    'What did I build with others?',
    'What became easier, clearer or more reliable afterward?',
    'What permitted evidence supports that?',
    'And what did I become able to do because I had to build it?',
    'Do not try to answer with one adjective.',
    'Do not write:',
    '“strategic.”',
    '“innovative.”',
    '“transformational.”',
    'Write what the work required you to notice, decide and make possible.',
    'That is how invisible work becomes legible.',
    '[SLIDE: Keep the Proof / Watch Next]',
    'If the hardest part is retrieving the evidence behind work like this, that is what Keep the Proof is designed for.',
    'It is a 60-minute career evidence system for preserving the work, decisions and proof you may need later — while the context is still clear.',
    'Use only information you are entitled to retain.',
    'Do not take confidential, proprietary, customer, employee or employer-owned material.',
    'You can find Keep the Proof at:',
    'temidayoafonja.com/keep-the-proof.',
    'And once you have the proof, there is another challenge:',
    'How do you explain a career that moved across several chapters without making it sound unfocused?',
    'Watch:',
    'How to Explain Your Career Change',
    'next.',
    'Because foundational work should not disappear simply because the infrastructure you built started working.',
]

MARKERS = [l for l in LINES if l.startswith("[SLIDE:")]
SPOKEN  = [l for l in LINES if not l.startswith("[SLIDE:")]
