# -*- coding: utf-8 -*-
"""Patched Video 6 spoken script.

Derived programmatically from SOURCE_Video_6_Code_Prompt_HIT_Final.txt by applying ONLY the exact
replacements authorised in that video's PATCH file. No wording is
retyped and no other paragraph is touched.
"""

LINES = ['Your workload can grow faster than your career.',
 'Across my own career, my scope has expanded beyond the job I was originally hired to do more '
 'than once.',
 'That taught me not to use volume as the test.',
 'Before you call more responsibility growth, run it through the CAR test: did the problem get '
 'more complex, did your authority expand, and what did the work return to your career?',
 '[SLIDE: Core Distinction]',
 'I’m Temidayo Afonja. I help experienced professionals understand what their work is building in '
 'them, what they can carry forward and what may need to change before the next move.',
 'More responsibility can absolutely be part of growth.',
 'Growth can be demanding.',
 'There are seasons when taking on extra work is reasonable — a launch, a vacancy, a transition, a '
 'problem that simply needs to be carried for a while.',
 'But there is another possibility.',
 'The organization may have learned that you are dependable enough to absorb more.',
 'Those are not the same thing.',
 'Being busier tells me that the workload changed.',
 'It does not tell me what the work is building in you.',
 '[SLIDE: More Work / Real Growth]',
 'That is the distinction I want you to make.',
 'More work can mean more volume, more coordination and more availability.',
 'Real growth should change something deeper.',
 'The problems you can handle.',
 'The judgment you can exercise.',
 'Or the evidence you will be able to carry into another context.',
 'A career can look successful from the outside while the work underneath it has stopped adding '
 'very much new judgment.',
 'You can still be doing good work.',
 'You can still be valued.',
 'You can still be the person everyone depends on.',
 'But those facts alone do not tell you whether your career is still compounding.',
 '[SLIDE: Three Tests]',
 'I call this the CAR test: Complexity, Authority and Return.',
 'Did the problem become more complex?',
 'Did your authority expand?',
 'And what did the additional work return to your career?',
 '[SLIDE: Complexity]',
 'The first test is complexity.',
 'Are you handling a meaningfully different problem?',
 'Or simply more units of the same one?',
 'Repetition can build speed, confidence and reliability.',
 'Those things matter.',
 'But doing eight versions of a problem you already knew how to solve does not necessarily expand '
 'your range simply because last year you handled three.',
 'Your capacity may be increasing.',
 'Your workload is certainly increasing.',
 'The question is whether the class of problem changed.',
 'Complexity usually appears when some of the variables change.',
 'A different customer.',
 'A new system.',
 'A regulation you have not worked with before.',
 'A stakeholder group with different incentives.',
 'Incomplete instructions.',
 'Conflicting priorities.',
 'A decision where the answer that worked last time cannot simply be copied.',
 'That is where judgment has to stretch.',
 'Think about the difference between receiving more recurring requests and being asked to '
 'understand why the requests keep recurring.',
 'The first is additional volume.',
 'The second may require diagnosis, redesign and influence.',
 'Or think about the difference between coordinating more meetings and being responsible for '
 'helping people with competing interests reach a decision.',
 'From the outside, both may look like more work.',
 'But the work is forming something different.',
 '[SLIDE: Capability Question]',
 'So ask:',
 'What can I credibly do now that I could not credibly do before?',
 'Not:',
 'What am I doing more of?',
 'What am I doing faster?',
 'What have people become more comfortable handing me?',
 'Ask what became possible because you encountered this work.',
 'Can you diagnose something you could not diagnose before?',
 'Can you make a decision with less help?',
 'Can you work through a type of ambiguity that used to stop you?',
 'Can you operate across a context you did not previously understand?',
 'If the only answer is:',
 '“I can carry more of the same thing,”',
 'call that capacity use.',
 'It may be valuable.',
 'But do not automatically call it career growth.',
 '[SLIDE: Accountability / Authority]',
 'The second test is authority.',
 'As your responsibility increased, did anything change about what you can influence or decide?',
 'There are three words that often get blurred together.',
 'Responsibility is what you are expected to carry.',
 'Accountability is what you will answer for.',
 'Authority is what you can influence, change, approve, stop, prioritize or recommend with some '
 'expectation that your judgment will matter.',
 'Those do not always grow together.',
 'You may become accountable for a deadline without being able to reduce the scope, change the '
 'sequence or secure the people needed to meet it.',
 'You may be told to own an outcome while the decisions that shape that outcome still sit '
 'somewhere else.',
 'You may start attending more senior meetings and still only be there to provide information.',
 'Exposure can be useful.',
 'Observation is part of learning.',
 'But eventually, if this is supposed to be growth, your judgment needs somewhere to go.',
 '[SLIDE: Authority Warning]',
 'Accountability without authority is a warning, not a development plan.',
 'That does not mean you need complete control.',
 'Very few meaningful roles come with complete control.',
 'But ask:',
 'Which decisions now belong to me?',
 'What can I change when the plan is not working?',
 'Where am I expected to recommend a direction rather than simply execute one?',
 'What access, sponsorship, information or resources come with the expanded responsibility?',
 'If the organization increases what you answer for while your ability to influence the outcome '
 'stays exactly the same, the role may be transferring risk without developing much additional '
 'judgment.',
 'That can make you more exposed.',
 'It does not necessarily make you more capable.',
 '[SLIDE: Return]',
 'The third test is return.',
 'More work costs something.',
 'Time.',
 'Attention.',
 'Energy.',
 'Sometimes flexibility.',
 'Sometimes visibility for other work you are no longer able to take on.',
 'So what is coming back to your career?',
 'I would look in three places.',
 'Capability.',
 'Evidence.',
 'Recognition.',
 'Capability means the work changed what you can handle.',
 'You understand a new system.',
 'You can navigate a more difficult stakeholder environment.',
 'You can make a type of judgment that was previously outside your range.',
 'Evidence means the work left you with something you can explain.',
 'A permitted result.',
 'A decision you influenced.',
 'A problem you can describe without relying on confidential material or company shorthand.',
 'Another context can hear what you did and why it mattered.',
 'Recognition means the organization has acknowledged the expanded contribution in something more '
 'concrete than praise.',
 'That might mean greater decision authority.',
 'Formal scope.',
 'Compensation.',
 'Title.',
 'Sponsorship.',
 'Visibility that is connected to real work.',
 'Or a credible review point where the expanded responsibility will actually be assessed.',
 'Not every stretch assignment will return all three immediately.',
 'Sometimes the capability comes first.',
 'Sometimes you accept a defined period of extra load because the evidence will be unusually '
 'valuable.',
 'Sometimes the experience gives you access to a context you could not otherwise enter.',
 'But I want the return to be visible somewhere.',
 'Because reliability can increase how much an organization gives you before it increases the '
 'authority, support or recognition it gives you.',
 'Praise is welcome.',
 'Praise alone is not role design.',
 'Ask:',
 'What will this work make me better able to do?',
 'What evidence will I be able to point to six or twelve months from now?',
 'And what has the organization said will change if this expanded responsibility becomes '
 'permanent?',
 'If no one can name a return and nothing is scheduled to change, the organization may be '
 'benefiting from your reliability more than your career is benefiting from the work.',
 '[SLIDE: Pattern Read]',
 'Now put the CAR test together.',
 'If complexity, authority and return are all expanding, you probably have a strong growth case.',
 'The work can still be hard.',
 'You can still need support.',
 'You can still decide the workload is too much.',
 'But the career return is visible.',
 'If complexity is increasing but authority or support has not caught up, you may be in an '
 'unsustainable stretch.',
 'That does not automatically mean you should leave or refuse the work.',
 'It tells you what needs to be redesigned.',
 'Which decisions need to move?',
 'What support is missing?',
 'What should come off your plate?',
 'If volume increased but complexity, authority and return did not, the role has expanded mainly '
 'as workload.',
 'That may be reasonable for a short season.',
 'Someone leaves.',
 'A launch is underway.',
 'A transition needs coverage.',
 'But temporary work needs a boundary.',
 'Otherwise temporary coverage quietly becomes the permanent design of your role.',
 'And that is where dependable people can lose years without realizing the career has stopped '
 'compounding.',
 'This is not a moral judgment about taking on extra work.',
 'Growth can be tiring.',
 'Ordinary work matters.',
 'Reliability is valuable.',
 'The goal is accuracy.',
 'Is the cost you are carrying building something you can use — or consuming the space where '
 'development could have happened?',
 '[SLIDE: Before the Scope Expands Again]',
 'Before your scope expands again, look at what has been added during the last six to twelve '
 'months.',
 'Then ask three questions.',
 'What should come off my plate?',
 'If something important is becoming a permanent part of your role, it is reasonable to ask '
 'whether everything from the old role still belongs there too.',
 'Which decisions need to belong to me?',
 'If you are accountable for the outcome, identify where decision rights or influence need to '
 'change.',
 'And:',
 'How and when will this scope be reviewed?',
 'Do not leave “we will revisit this later” undefined.',
 'Later has a way of becoming permanent.',
 'A review point does not guarantee a promotion or compensation change.',
 'It creates a moment where the organization has to acknowledge what the role has actually become.',
 'That is a much stronger conversation than saying only:',
 '“I have too much work.”',
 'You are showing the design problem.',
 'The workload changed.',
 'Now what needs to change around it?',
 '[SLIDE: Capability Formation Field Kit]',
 'If you want a structured way to examine what your current work is actually building in you, that '
 'is what the Capability Formation Field Kit is designed to help you do.',
 'It gives you a private, evidence-led read of your recent work so you can see where capability is '
 'accumulating, what appears portable and where the role may need a boundary or redesign.',
 'You can find it at:',
 'temidayoafonja.com/fieldkit.',
 '[SLIDE: Watch Next]',
 'One of the hardest versions of this problem is when the work really did expand your capability — '
 'but almost none of the value is easy to show because you built something that did not exist '
 'before.',
 'That is what we are going to tackle next.',
 'Watch:',
 'How to Show Your Impact at Work When You Built It From Scratch.',
 'More work can be part of growth.',
 'It is not proof of it.']

SPOKEN = ['Your workload can grow faster than your career.',
 'Across my own career, my scope has expanded beyond the job I was originally hired to do more '
 'than once.',
 'That taught me not to use volume as the test.',
 'Before you call more responsibility growth, run it through the CAR test: did the problem get '
 'more complex, did your authority expand, and what did the work return to your career?',
 'I’m Temidayo Afonja. I help experienced professionals understand what their work is building in '
 'them, what they can carry forward and what may need to change before the next move.',
 'More responsibility can absolutely be part of growth.',
 'Growth can be demanding.',
 'There are seasons when taking on extra work is reasonable — a launch, a vacancy, a transition, a '
 'problem that simply needs to be carried for a while.',
 'But there is another possibility.',
 'The organization may have learned that you are dependable enough to absorb more.',
 'Those are not the same thing.',
 'Being busier tells me that the workload changed.',
 'It does not tell me what the work is building in you.',
 'That is the distinction I want you to make.',
 'More work can mean more volume, more coordination and more availability.',
 'Real growth should change something deeper.',
 'The problems you can handle.',
 'The judgment you can exercise.',
 'Or the evidence you will be able to carry into another context.',
 'A career can look successful from the outside while the work underneath it has stopped adding '
 'very much new judgment.',
 'You can still be doing good work.',
 'You can still be valued.',
 'You can still be the person everyone depends on.',
 'But those facts alone do not tell you whether your career is still compounding.',
 'I call this the CAR test: Complexity, Authority and Return.',
 'Did the problem become more complex?',
 'Did your authority expand?',
 'And what did the additional work return to your career?',
 'The first test is complexity.',
 'Are you handling a meaningfully different problem?',
 'Or simply more units of the same one?',
 'Repetition can build speed, confidence and reliability.',
 'Those things matter.',
 'But doing eight versions of a problem you already knew how to solve does not necessarily expand '
 'your range simply because last year you handled three.',
 'Your capacity may be increasing.',
 'Your workload is certainly increasing.',
 'The question is whether the class of problem changed.',
 'Complexity usually appears when some of the variables change.',
 'A different customer.',
 'A new system.',
 'A regulation you have not worked with before.',
 'A stakeholder group with different incentives.',
 'Incomplete instructions.',
 'Conflicting priorities.',
 'A decision where the answer that worked last time cannot simply be copied.',
 'That is where judgment has to stretch.',
 'Think about the difference between receiving more recurring requests and being asked to '
 'understand why the requests keep recurring.',
 'The first is additional volume.',
 'The second may require diagnosis, redesign and influence.',
 'Or think about the difference between coordinating more meetings and being responsible for '
 'helping people with competing interests reach a decision.',
 'From the outside, both may look like more work.',
 'But the work is forming something different.',
 'So ask:',
 'What can I credibly do now that I could not credibly do before?',
 'Not:',
 'What am I doing more of?',
 'What am I doing faster?',
 'What have people become more comfortable handing me?',
 'Ask what became possible because you encountered this work.',
 'Can you diagnose something you could not diagnose before?',
 'Can you make a decision with less help?',
 'Can you work through a type of ambiguity that used to stop you?',
 'Can you operate across a context you did not previously understand?',
 'If the only answer is:',
 '“I can carry more of the same thing,”',
 'call that capacity use.',
 'It may be valuable.',
 'But do not automatically call it career growth.',
 'The second test is authority.',
 'As your responsibility increased, did anything change about what you can influence or decide?',
 'There are three words that often get blurred together.',
 'Responsibility is what you are expected to carry.',
 'Accountability is what you will answer for.',
 'Authority is what you can influence, change, approve, stop, prioritize or recommend with some '
 'expectation that your judgment will matter.',
 'Those do not always grow together.',
 'You may become accountable for a deadline without being able to reduce the scope, change the '
 'sequence or secure the people needed to meet it.',
 'You may be told to own an outcome while the decisions that shape that outcome still sit '
 'somewhere else.',
 'You may start attending more senior meetings and still only be there to provide information.',
 'Exposure can be useful.',
 'Observation is part of learning.',
 'But eventually, if this is supposed to be growth, your judgment needs somewhere to go.',
 'Accountability without authority is a warning, not a development plan.',
 'That does not mean you need complete control.',
 'Very few meaningful roles come with complete control.',
 'But ask:',
 'Which decisions now belong to me?',
 'What can I change when the plan is not working?',
 'Where am I expected to recommend a direction rather than simply execute one?',
 'What access, sponsorship, information or resources come with the expanded responsibility?',
 'If the organization increases what you answer for while your ability to influence the outcome '
 'stays exactly the same, the role may be transferring risk without developing much additional '
 'judgment.',
 'That can make you more exposed.',
 'It does not necessarily make you more capable.',
 'The third test is return.',
 'More work costs something.',
 'Time.',
 'Attention.',
 'Energy.',
 'Sometimes flexibility.',
 'Sometimes visibility for other work you are no longer able to take on.',
 'So what is coming back to your career?',
 'I would look in three places.',
 'Capability.',
 'Evidence.',
 'Recognition.',
 'Capability means the work changed what you can handle.',
 'You understand a new system.',
 'You can navigate a more difficult stakeholder environment.',
 'You can make a type of judgment that was previously outside your range.',
 'Evidence means the work left you with something you can explain.',
 'A permitted result.',
 'A decision you influenced.',
 'A problem you can describe without relying on confidential material or company shorthand.',
 'Another context can hear what you did and why it mattered.',
 'Recognition means the organization has acknowledged the expanded contribution in something more '
 'concrete than praise.',
 'That might mean greater decision authority.',
 'Formal scope.',
 'Compensation.',
 'Title.',
 'Sponsorship.',
 'Visibility that is connected to real work.',
 'Or a credible review point where the expanded responsibility will actually be assessed.',
 'Not every stretch assignment will return all three immediately.',
 'Sometimes the capability comes first.',
 'Sometimes you accept a defined period of extra load because the evidence will be unusually '
 'valuable.',
 'Sometimes the experience gives you access to a context you could not otherwise enter.',
 'But I want the return to be visible somewhere.',
 'Because reliability can increase how much an organization gives you before it increases the '
 'authority, support or recognition it gives you.',
 'Praise is welcome.',
 'Praise alone is not role design.',
 'Ask:',
 'What will this work make me better able to do?',
 'What evidence will I be able to point to six or twelve months from now?',
 'And what has the organization said will change if this expanded responsibility becomes '
 'permanent?',
 'If no one can name a return and nothing is scheduled to change, the organization may be '
 'benefiting from your reliability more than your career is benefiting from the work.',
 'Now put the CAR test together.',
 'If complexity, authority and return are all expanding, you probably have a strong growth case.',
 'The work can still be hard.',
 'You can still need support.',
 'You can still decide the workload is too much.',
 'But the career return is visible.',
 'If complexity is increasing but authority or support has not caught up, you may be in an '
 'unsustainable stretch.',
 'That does not automatically mean you should leave or refuse the work.',
 'It tells you what needs to be redesigned.',
 'Which decisions need to move?',
 'What support is missing?',
 'What should come off your plate?',
 'If volume increased but complexity, authority and return did not, the role has expanded mainly '
 'as workload.',
 'That may be reasonable for a short season.',
 'Someone leaves.',
 'A launch is underway.',
 'A transition needs coverage.',
 'But temporary work needs a boundary.',
 'Otherwise temporary coverage quietly becomes the permanent design of your role.',
 'And that is where dependable people can lose years without realizing the career has stopped '
 'compounding.',
 'This is not a moral judgment about taking on extra work.',
 'Growth can be tiring.',
 'Ordinary work matters.',
 'Reliability is valuable.',
 'The goal is accuracy.',
 'Is the cost you are carrying building something you can use — or consuming the space where '
 'development could have happened?',
 'Before your scope expands again, look at what has been added during the last six to twelve '
 'months.',
 'Then ask three questions.',
 'What should come off my plate?',
 'If something important is becoming a permanent part of your role, it is reasonable to ask '
 'whether everything from the old role still belongs there too.',
 'Which decisions need to belong to me?',
 'If you are accountable for the outcome, identify where decision rights or influence need to '
 'change.',
 'And:',
 'How and when will this scope be reviewed?',
 'Do not leave “we will revisit this later” undefined.',
 'Later has a way of becoming permanent.',
 'A review point does not guarantee a promotion or compensation change.',
 'It creates a moment where the organization has to acknowledge what the role has actually become.',
 'That is a much stronger conversation than saying only:',
 '“I have too much work.”',
 'You are showing the design problem.',
 'The workload changed.',
 'Now what needs to change around it?',
 'If you want a structured way to examine what your current work is actually building in you, that '
 'is what the Capability Formation Field Kit is designed to help you do.',
 'It gives you a private, evidence-led read of your recent work so you can see where capability is '
 'accumulating, what appears portable and where the role may need a boundary or redesign.',
 'You can find it at:',
 'temidayoafonja.com/fieldkit.',
 'One of the hardest versions of this problem is when the work really did expand your capability — '
 'but almost none of the value is easy to show because you built something that did not exist '
 'before.',
 'That is what we are going to tackle next.',
 'Watch:',
 'How to Show Your Impact at Work When You Built It From Scratch.',
 'More work can be part of growth.',
 'It is not proof of it.']

MARKERS = ['[SLIDE: Core Distinction]',
 '[SLIDE: More Work / Real Growth]',
 '[SLIDE: Three Tests]',
 '[SLIDE: Complexity]',
 '[SLIDE: Capability Question]',
 '[SLIDE: Accountability / Authority]',
 '[SLIDE: Authority Warning]',
 '[SLIDE: Return]',
 '[SLIDE: Pattern Read]',
 '[SLIDE: Before the Scope Expands Again]',
 '[SLIDE: Capability Formation Field Kit]',
 '[SLIDE: Watch Next]']

